# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Libro', '0003_auto_20171204_1645'),
        ('Evento', '0001_initial'),
        ('Investigador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.IntegerField()),
                ('Certificado', models.CharField(max_length=5)),
                ('Titulo_Publicacion', models.CharField(max_length=25)),
                ('Tipo_Publicacion', models.CharField(max_length=15)),
                ('Financiamiento', models.CharField(max_length=7)),
                ('Url_publicacion', models.URLField()),
                ('Informe', models.FileField(upload_to='')),
                ('Datos', models.CharField(max_length=25)),
                ('Asistencia', models.CharField(max_length=5)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Evento.evento')),
                ('investigador', models.ManyToManyField(to='Investigador.investigador')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Libro.libro')),
            ],
        ),
    ]
